services:
  - type: web
    name: website-watcher
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 8888
      - key: CHECK_INTERVAL
        value: 300
      - key: AUTH_PASSWORD
        value: 1033
      - key: ENVIRONMENT
        value: production
    disk:
      name: website-watcher-disk
      mountPath: /opt/render/project/data
      sizeGB: 1